apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-mentions-bot-secret-provider
  namespace: aks-mentions-bot
  labels:
    app: aks-mentions-bot
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "YOUR_MANAGED_IDENTITY_CLIENT_ID"
    keyvaultName: "YOUR_KEYVAULT_NAME"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: teams-webhook-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: reddit-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: reddit-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: twitter-bearer-token
          objectType: secret
          objectVersion: ""
        - |
          objectName: youtube-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: notification-email
          objectType: secret
          objectVersion: ""
        - |
          objectName: smtp-password
          objectType: secret
          objectVersion: ""
    tenantId: "YOUR_TENANT_ID"
  secretObjects:
  - secretName: aks-mentions-bot-secrets
    type: Opaque
    data:
    - objectName: teams-webhook-url
      key: TEAMS_WEBHOOK_URL
    - objectName: reddit-client-id
      key: REDDIT_CLIENT_ID
    - objectName: reddit-client-secret
      key: REDDIT_CLIENT_SECRET
    - objectName: twitter-bearer-token
      key: TWITTER_BEARER_TOKEN
    - objectName: youtube-api-key
      key: YOUTUBE_API_KEY
    - objectName: notification-email
      key: NOTIFICATION_EMAIL
    - objectName: smtp-password
      key: SMTP_PASSWORD
---
# Additional ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-mentions-bot-email-config
  namespace: aks-mentions-bot
data:
  SMTP_HOST: "smtp.office365.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "your-email@company.com"
